In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')
df = df.dropna(axis = 0, how ='any')

In [3]:
x1 = df.iloc[:, :-2]
y1 = df.iloc[:, -2]
x1

ID   Age     BusinessTravel  DailyRate              Department  \
0        1  44.0      Travel_Rarely     1376.0         Human Resources   
1        2  25.0         Non-Travel      675.0  Research & Development   
2        3  57.0      Travel_Rarely      210.0                   Sales   
3        4  47.0      Travel_Rarely     1180.0  Research & Development   
4        5  22.0      Travel_Rarely      391.0  Research & Development   
...    ...   ...                ...        ...                     ...   
1225  1226  29.0      Travel_Rarely      806.0  Research & Development   
1226  1227  41.0      Travel_Rarely      582.0  Research & Development   
1227  1228  36.0      Travel_Rarely     1456.0                   Sales   
1228  1229  23.0      Travel_Rarely      885.0  Research & Development   
1229  1230  31.0  Travel_Frequently      754.0                   Sales   

      DistanceFromHome  Gender  HourlyRate  JobInvolvement  JobLevel  ...  \
0                    1    Male        91.0             2.0         3  ...   
1                    5    Male        85.0             4.0         2  ...   
2                   29    Male        56.0             2.0         4  ...   
3                   25    Male        84.0             3.0         3  ...   
4                    7    Male        75.0             3.0         1  ...   
...                ...     ...         ...             ...       ...  ...   
1225                 7  Female        39.0             3.0         1  ...   
1226                28  Female        60.0             2.0         4  ...   
1227                13    Male        96.0             2.0         2  ...   
1228                 4    Male        58.0             4.0         1  ...   
1229                26    Male        63.0             3.0         2  ...   

        EducationField  EmployeeCount EmployeeNumber  EnvironmentSatisfaction  \
0              Medical              1           1098                      2.0   
1        Life Sciences              1            369                      2.0   
2            Marketing              1            568                      1.0   
3              Medical              1           1993                      1.0   
4        Life Sciences              1           1878                      4.0   
...                ...            ...            ...                      ...   
1225  Technical Degree              1           1299                      2.0   
1226     Life Sciences              1           2034                      1.0   
1227         Marketing              1           1733                      2.0   
1228           Medical              1            705                      1.0   
1229         Marketing              1           1967                      1.0   

      WorkLifeBalance  YearsInCurrentRole YearsSinceLastPromotion  \
0                 3.0                   6                     3.0   
1                 3.0                   3                     1.0   
2                 2.0                   0                     0.0   
3                 3.0                  14                    12.0   
4                 3.0                   0                     0.0   
...               ...                 ...                     ...   
1225              3.0                   7                     7.0   
1226              3.0                   7                     0.0   
1227              3.0                   2                     2.0   
1228              4.0                   2                     0.0   
1229              3.0                   7                     0.0   

     YearsWithCurrManager  FormalWarnings  ProjectsContributed  
0                       6               0                 15.0  
1                       5               0                  7.0  
2                       0               0                  3.0  
3                      11               0                 14.0  
4                       0               0                  5.0  
..

In [4]:
X = df.iloc[:, :-2].values
y = df.iloc[:, -2].values
y_reg = df.iloc[:,-1]

In [5]:
y_reg

0       20
1        6
2        1
3       17
4        1
        ..
1225     7
1226    20
1227     2
1228     3
1229    10
Name: YearsAtCompany, Length: 1213, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
X[:,4] = le.fit_transform(X[:,4])
X[:,6] = le.fit_transform(X[:,6])
X[:,10] = le.fit_transform(X[:,10])
X[:,12] = le.fit_transform(X[:,12])
X[:,16] = le.fit_transform(X[:,16])
X[:,17] = le.fit_transform(X[:,17])
X[:,32] = le.fit_transform(X[:,32])

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [8]:
X_train.shape

(970, 42)

In [9]:
X_test.shape

(243, 42)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,1:42] = sc.fit_transform(X_train[:,1:42])
X_test[:,1:42] = sc.fit_transform(X_test[:,1:42])

In [11]:
new_data = pd.DataFrame(X_train)
new_data

0         1         2          3        4          5         6   \
0     985  0.827524 -0.876572  -0.906323 -0.47902   -1.01841  0.811246   
1     358  -1.49337 -0.876572  -0.385371  1.40215 -0.0219579  0.811246   
2     685  -1.27233  0.607328  0.0433557  1.40215  -0.146514  0.811246   
3     680  0.717005  0.607328  -0.544897 -0.47902   0.227155  0.811246   
4     996 -0.388183 -0.876572  0.0857299 -0.47902    2.46917  -1.23267   
..    ...       ...       ...        ...      ...        ...       ...   
965  1060 -0.167146  0.607328   0.858435 -0.47902    1.47272  -1.23267   
966  1113  -0.71974  0.607328   -1.37493 -0.47902  -0.271071  0.811246   
967  1148 -0.167146  0.607328    1.02544  1.40215  -0.644741  0.811246   
968   872   1.15908  0.607328    1.07778  1.40215  -0.893854  -1.23267   
969  1144   1.93271  0.607328  -0.609704 -0.47902  -0.146514  -1.23267   

           7         8          9   ...        32 33        34        35  \
0     1.62802  0.360057  -0.965185  ...  0.545404  0   1.18329  0.264973   
1    -1.63209  0.360057  -0.965185  ...  -0.20183  0   1.64123   1.18291   
2   -0.446597   1.74051 -0.0336134  ... -0.949065  0  -0.96763   1.18291   
3    -1.78028  0.360057   0.897958  ... -0.949065  0   1.53814  -1.57091   
4   -0.594783   -1.0204 -0.0336134  ...  0.545404  0 -0.186559  -1.57091   
..        ...       ...        ...  ...       ... ..       ...       ...   
965  -0.74297  0.360057 -0.0336134  ... -0.949065  0 -0.501763   1.18291   
966 -0.891156   -1.0204  -0.965185  ...  0.545404  0  0.820506 -0.652969   
967  0.985874  0.360057   0.897958  ...   2.03987  0 -0.188542   1.18291   
968 -0.940552   1.74051    1.82953  ... -0.949065  0  0.953328 -0.652969   
969  -1.18753  0.360057 -0.0336134  ... -0.949065  0  -1.22336  0.264973   

           36         37         38        39 40         41  
0    -1.07079  -0.320793 -0.0437542 -0.293833  0   -1.03627  
1    -1.07079   -1.17959  -0.358137  -1.15232  0    0.72597  
2    0.346216  -0.607057  -0.358137 -0.579995  0   0.138557  
3    0.346216    1.39679  -0.672519   1.42314  0    0.72597  
4    0.346216   0.824264   0.270628   1.13698  0    0.25604  
..        ...        ...        ...       ... ..        ...  
965  -2.48779      0.538  -0.672519  0.850817  0    1.07842  
966  -1.07079 -0.0345288  -0.358137 -0.866158  0  -0.918787  
967  0.346216   0.824264    0.58501  0.850817  0   0.138557  
968  0.346216  -0.607057  -0.358137 -0.579995  0    1.54835  
969  0.346216   -1.17959  -0.672519  -1.15232  0  0.0210742  

[970 rows x 42 columns]

In [12]:
#from sklearn.ensemble import RandomForestClassifier
#classifier = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 42)
#classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=50, random_state=42)

In [ ]:
#from sklearn.svm import SVC #ran on a different notebook but used this
#classifier = SVC(kernel='linear',probability=True)
#classifier.fit(X_train,y_train)

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[209   5]
 [ 24   5]]


0.8806584362139918

In [14]:
import pickle
#pickle.dump(classifier,open('classifier.pkl','wb'))

In [15]:
y_pred = classifier.predict_proba(X_test)
y_pred

array([[0.72, 0.28],
       [0.94, 0.06],
       [0.66, 0.34],
       [0.9 , 0.1 ],
       [0.82, 0.18],
       [0.84, 0.16],
       [0.8 , 0.2 ],
       [0.8 , 0.2 ],
       [0.48, 0.52],
       [0.96, 0.04],
       [0.72, 0.28],
       [0.86, 0.14],
       [0.58, 0.42],
       [0.84, 0.16],
       [0.88, 0.12],
       [0.76, 0.24],
       [0.86, 0.14],
       [0.8 , 0.2 ],
       [0.94, 0.06],
       [0.9 , 0.1 ],
       [0.84, 0.16],
       [0.94, 0.06],
       [0.82, 0.18],
       [0.9 , 0.1 ],
       [0.28, 0.72],
       [0.76, 0.24],
       [0.78, 0.22],
       [0.92, 0.08],
       [0.92, 0.08],
       [0.62, 0.38],
       [0.98, 0.02],
       [0.84, 0.16],
       [0.88, 0.12],
       [1.  , 0.  ],
       [0.84, 0.16],
       [0.92, 0.08],
       [0.94, 0.06],
       [0.86, 0.14],
       [0.8 , 0.2 ],
       [0.76, 0.24],
       [0.74, 0.26],
       [0.92, 0.08],
       [0.9 , 0.1 ],
       [0.8 , 0.2 ],
       [0.82, 0.18],
       [0.84, 0.16],
       [0.8 , 0.2 ],
       [0.98,

In [1010]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y_reg, test_size = 0.2, random_state = 42)
X_train2
y_train2

984      5
357      1
684      3
679     10
995     13
        ..
1059    10
1112     6
1147     8
871      3
1143     1
Name: YearsAtCompany, Length: 970, dtype: int64

In [974]:
"""sc_y = StandardScaler()
y_train2 = np.array(y_train2)
y_train2 = y_train2.reshape(-1,1)
y_train2 = sc_y.fit_transform(y_train2)
y_train2 = y_train2.reshape(len(y_train2),)
y_train2.shape"""

(970,)

In [975]:
#from sklearn.svm import SVR
#regressor = SVR(kernel = 'linear')
#regressor.fit(X_train,y_train2)

SVR(kernel='linear')

In [1277]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=8)
regressor.fit(X_train2, y_train2)


RandomForestRegressor(n_estimators=8)

In [1278]:
ypred2 = regressor.predict(X_test2)


In [1279]:
from sklearn.metrics import r2_score
print(r2_score(ypred2,y_test2))

0.8969100504620502


In [1280]:
#pickle.dump(regressor,open('regres8969.pkl','wb'))

In [1283]:
#START THE MAIN EXECUTION FROM HERE AFTER DOWNLOADING THE PICKELS
df_final = pd.read_csv('test_new.csv') 

In [1284]:
X_final = df_final.iloc[:].values
X_final_scaled = df_final.iloc[:].values

In [1285]:
X_final.shape
X_final_scaled.shape

(240, 42)

In [1286]:
X_final[:,2] = le.fit_transform(X_final[:,2])
X_final[:,4] = le.fit_transform(X_final[:,4])
X_final[:,6] = le.fit_transform(X_final[:,6])
X_final[:,10] = le.fit_transform(X_final[:,10])
X_final[:,12] = le.fit_transform(X_final[:,12])
X_final[:,16] = le.fit_transform(X_final[:,16])
X_final[:,17] = le.fit_transform(X_final[:,17])
X_final[:,32] = le.fit_transform(X_final[:,32])

In [1287]:
X_final_scaled[:,2] = le.fit_transform(X_final_scaled[:,2])
X_final_scaled[:,4] = le.fit_transform(X_final_scaled[:,4])
X_final_scaled[:,6] = le.fit_transform(X_final_scaled[:,6])
X_final_scaled[:,10] = le.fit_transform(X_final_scaled[:,10])
X_final_scaled[:,12] = le.fit_transform(X_final_scaled[:,12])
X_final_scaled[:,16] = le.fit_transform(X_final_scaled[:,16])
X_final_scaled[:,17] = le.fit_transform(X_final_scaled[:,17])
X_final_scaled[:,32] = le.fit_transform(X_final_scaled[:,32])

In [1288]:
X_final_scaled[:,1:42] = sc.fit_transform(X_final_scaled[:,1:42])

In [1289]:
X_final

array([[1, 27, 2, ..., 2, 0, 14],
       [2, 26, 2, ..., 0, 0, 30],
       [3, 50, 2, ..., 2, 0, 3],
       ...,
       [238, 37, 0, ..., 0, 0, 10],
       [239, 44, 0, ..., 2, 0, 7],
       [240, 28, 2, ..., 2, 0, 28]], dtype=object)

In [1290]:
classifier = pickle.load(open('classifier.pkl','rb'))
regressor = pickle.load(open('regres8969.pkl','rb'))

C:\Users\yashv\anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator SVC from version 0.23.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(


In [1291]:
y_final_prob_rf = classifier.predict_proba(X_final_scaled)

In [1292]:
y_final_reg = regressor.predict(X_final)
y_final_regg=[]

In [1293]:
for i in range(len(y_final_reg)):
    y_final_regg.append(int(y_final_reg[i]))

In [1294]:
y_final_regg = np.array(y_final_regg)

In [1295]:
list_final = np.concatenate((X_final[:,0].reshape(len(X_final[:,0]),1),y_final_prob_rf[:,1].reshape(len(y_final_prob_rf),1),y_final_regg.reshape(len(y_final_regg),1)),1)
final_csv = pd.DataFrame(list_final,columns = ('ID','Attrition','YearsAtCompany'))
final_csv

ID  Attrition YearsAtCompany
0      1   0.275676              2
1      2    0.57169              3
2      3   0.089634              2
3      4    0.62303              5
4      5  0.0829638              3
..   ...        ...            ...
235  236    0.26534              0
236  237  0.0860502              4
237  238  0.0365796              0
238  239   0.110237              3
239  240        0.5              2

[240 rows x 3 columns]

In [1296]:
submission = final_csv.to_csv('peaky.csv') #INSERT THE CSV NAME HERE:) 